# Generated by Django 6.0.3 on 2026-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CONCOURS', 'Concours'), ('EVENT', 'Événement'), ('STAGE', 'Stage'), ('PROGRAM', 'Programme'), ('FORMATION', 'Formation'), ('COMPETITION', 'Compétition')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_audience', models.JSONField(default=list)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('prize', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
