# Generated by Django 6.0.3 on 2026-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
