services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=takku_db
      - POSTGRES_USER=takku_user
      - POSTGRES_PASSWORD=takku_pass

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://takku_user:takku_pass@db:5432/takku_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend # À créer si besoin, mais Vercel est préférable
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
