# Generated by Django 6.0.3 on 2026-03-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('LICENSE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat')], max_length=20)),
                ('coverage_percent', models.IntegerField(default=100)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('covers_tuition', models.BooleanField(default=True)),
                ('covers_living', models.BooleanField(default=False)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('age_limit', models.IntegerField(blank=True, null=True)),
                ('nationality_requirements', models.JSONField(default=list)),
                ('financial_need_required', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('application_link', models.URLField()),
                ('required_documents', models.JSONField(default=list)),
                ('selection_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.country')),
                ('fields', models.ManyToManyField(related_name='scholarships', to='careers.career')),
            ],
        ),
    ]
