# Generated by Django 6.0.3 on 2026-03-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('average_tuition_public', models.IntegerField(null=True)),
                ('average_tuition_private', models.IntegerField(null=True)),
                ('living_cost_monthly', models.IntegerField(null=True)),
                ('visa_required', models.BooleanField(default=True)),
                ('language_test_required', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PUBLIC', 'Publique'), ('PRIVATE', 'Privée')], max_length=20)),
                ('is_partner', models.BooleanField(default=False)),
                ('tuition_fees_min', models.IntegerField(null=True)),
                ('tuition_fees_max', models.IntegerField(null=True)),
                ('application_fee', models.IntegerField(null=True)),
                ('living_cost_monthly', models.IntegerField(null=True)),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('required_documents', models.JSONField(default=list)),
                ('admission_procedure', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.country')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('LICENSE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], max_length=20)),
                ('duration_years', models.IntegerField()),
                ('tuition_fees', models.IntegerField(null=True)),
                ('requirements', models.JSONField(default=dict)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
        ),
    ]
