# Generated by Django 6.0.3 on 2026-03-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SANTE', 'Santé'), ('TECH', 'Technologie'), ('COMMERCE', 'Commerce & Gestion'), ('DROIT', 'Droit & Science Politique'), ('ENSEIGNEMENT', 'Enseignement'), ('ARTS', 'Arts & Design'), ('INGENIERIE', 'Ingénierie'), ('AUTRE', 'Autre')], max_length=50)),
                ('required_education', models.CharField(max_length=255)),
                ('salary_entry', models.IntegerField(help_text='Salaire débutant estimé au Sénégal (FCFA/mois)')),
                ('salary_5years', models.IntegerField(help_text='Salaire après 5 ans estimé (FCFA/mois)')),
                ('skills', models.JSONField(default=list)),
                ('market_demand', models.IntegerField(default=3, help_text='Demande du marché (1-5)')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BAC', 'Baccalauréat'), ('LICENSE', 'Licence (Bac+3)'), ('MASTER', 'Master (Bac+5)'), ('DOCTORAT', 'Doctorat (Bac+8+)')], max_length=20)),
                ('degree_name', models.CharField(max_length=255)),
                ('duration_years', models.IntegerField()),
                ('description', models.TextField()),
                ('available_senegal', models.BooleanField(default=True)),
                ('available_countries', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=dict)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='careers.career')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
