# Generated by Django 6.0.3 on 2026-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ACADEMIC', 'Académique'), ('INTERESTS', "Centres d'intérêt"), ('ASPIRATIONS', 'Aspirations professionnelles')], max_length=20)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('SINGLE', 'Choix unique'), ('MULTIPLE', 'Choix multiple'), ('SCALE', 'Échelle (1-5)')], max_length=20)),
                ('options', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=1.0)),
                ('category_mapping', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OrientationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict)),
                ('recommended_careers', models.JSONField(default=list)),
                ('compatibility_scores', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
